# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AZ4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 480, 411, 201))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_3.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_3.addWidget(self.pushButton_19, 0, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_3.addWidget(self.pushButton_20, 1, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_3.addWidget(self.pushButton_22, 1, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_3.addWidget(self.pushButton_21, 1, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 2, 0, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 2, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_3.addWidget(self.pushButton_23, 2, 2, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 3, 0, 1, 2)
        self.pushButton_27 = QtWidgets.QPushButton(self.widget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_3.addWidget(self.pushButton_27, 3, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(480, 80, 421, 281))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 0, 0, 1, 2)
        self.pushButton_37 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_2.addWidget(self.pushButton_37, 0, 2, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_2.addWidget(self.pushButton_34, 0, 3, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_2.addWidget(self.pushButton_32, 1, 0, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_2.addWidget(self.pushButton_33, 1, 1, 1, 2)
        self.pushButton_29 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 1, 3, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_2.addWidget(self.pushButton_36, 2, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_2.addWidget(self.pushButton_30, 2, 1, 1, 2)
        self.pushButton_31 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_2.addWidget(self.pushButton_31, 2, 3, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 3, 0, 1, 3)
        self.pushButton_35 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_2.addWidget(self.pushButton_35, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton_14.setText(_translate("MainWindow", "7"))
        self.pushButton_18.setText(_translate("MainWindow", "8"))
        self.pushButton_19.setText(_translate("MainWindow", "9"))
        self.pushButton_20.setText(_translate("MainWindow", "4"))
        self.pushButton_22.setText(_translate("MainWindow", "5"))
        self.pushButton_21.setText(_translate("MainWindow", "6"))
        self.pushButton_24.setText(_translate("MainWindow", "1"))
        self.pushButton_25.setText(_translate("MainWindow", "2"))
        self.pushButton_23.setText(_translate("MainWindow", "3"))
        self.pushButton_26.setText(_translate("MainWindow", "0"))
        self.pushButton_27.setText(_translate("MainWindow", "."))
        self.pushButton_15.setText(_translate("MainWindow", "7"))
        self.pushButton_37.setText(_translate("MainWindow", "8"))
        self.pushButton_34.setText(_translate("MainWindow", "9"))
        self.pushButton_32.setText(_translate("MainWindow", "4"))
        self.pushButton_33.setText(_translate("MainWindow", "5"))
        self.pushButton_29.setText(_translate("MainWindow", "6"))
        self.pushButton_36.setText(_translate("MainWindow", "1"))
        self.pushButton_30.setText(_translate("MainWindow", "2"))
        self.pushButton_31.setText(_translate("MainWindow", "3"))
        self.pushButton_28.setText(_translate("MainWindow", "0"))
        self.pushButton_35.setText(_translate("MainWindow", "."))

